"""Generate op25's PCWIN config files from config/frequencies.py.

op25's `rx.py` reads a `trunk.tsv` (system definition) which in turn points at a
talkgroup-tags file and a whitelist. Rather than hand-maintain those alongside
the Python catalog, we derive them from `PCWIN` + `PCWIN_TALKGROUPS` so there's
a single source of truth. Encrypted talkgroups are excluded from the whitelist
so op25 never tries to follow them.

Run from the repo root:
    uv run python scripts/gen_op25_config.py

The generated files (config/op25/{trunk.tsv,tg_tags.tsv,whitelist.tsv}) are
committed; `tests/test_frequencies_p25.py` asserts they stay in sync with the
catalog. Re-run this script after editing PCWIN_TALKGROUPS.
"""

from __future__ import annotations

from pathlib import Path

from config.frequencies import PCWIN, active_talkgroups

OP25_DIR = Path(__file__).resolve().parent.parent / "config" / "op25"

_AUTOGEN = "# AUTO-GENERATED by scripts/gen_op25_config.py — do not edit by hand.\n"


def render_trunk_tsv() -> str:
    """The op25 system-definition row. Tab-separated, one system."""
    # str() gives the shortest round-trip repr — keeps 853.7125 intact (a
    # `%g` here would silently truncate it to 853.712).
    control = ",".join(str(mhz) for mhz in PCWIN.control_channels_mhz)
    header = (
        "Sysname\tControl Channel List\tOffset\tNAC\tModulation"
        "\tTGID Tags File\tWhitelist\tBlacklist\n"
    )
    # NAC column is 0 = auto-detect. NAC is per-channel and independent of the
    # System ID; on PCWIN the control-channel NAC is 0x3B1 while the SYSID is
    # 0x3BB. Hardcoding the SYSID here made op25 reject every frame
    # ("NAC check fail: received=3b1, expected=3bb"); 0 lets op25 lock whatever
    # NAC the control channel actually uses. (Verified live on the Pi.)
    row = (
        f"{PCWIN.name}\t{control}\t0\t0\tcqpsk"
        f"\ttg_tags.tsv\twhitelist.tsv\t\n"
    )
    return _AUTOGEN + header + row


def render_tg_tags_tsv() -> str:
    """`tgid<TAB>label` for every active (unencrypted) talkgroup."""
    lines = [_AUTOGEN]
    for tg in active_talkgroups():
        lines.append(f"{tg.dec}\t{tg.name}\n")
    return "".join(lines)


def render_whitelist_tsv() -> str:
    """One active talkgroup decimal ID per line."""
    lines = [_AUTOGEN]
    for tg in active_talkgroups():
        lines.append(f"{tg.dec}\n")
    return "".join(lines)


def generate() -> dict[str, str]:
    """Return {filename: content} for all generated files."""
    return {
        "trunk.tsv": render_trunk_tsv(),
        "tg_tags.tsv": render_tg_tags_tsv(),
        "whitelist.tsv": render_whitelist_tsv(),
    }


def main() -> int:
    OP25_DIR.mkdir(parents=True, exist_ok=True)
    for name, content in generate().items():
        (OP25_DIR / name).write_text(content)
        print(f"wrote {OP25_DIR / name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
